services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    working_dir: /app
    container_name: movie
    ports:
      - "9090:9090"  
    env_file:
      - ./api/.env
    depends_on:
      - postgres
      - redis    
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: reservationuser
      POSTGRES_PASSWORD: reservationpass
      POSTGRES_DB: moviesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379" 
    volumes:
      - redisdata:/data   
volumes:
  pgdata:
  redisdata: